[[ $- =~ i ]] || return 0

trap "date >> $HISTFILE; history -a" HUP INT QUIT KILL TERM

set -C -b -o vi
shopt -s extglob

# set some basic items

umask 0022
export HISTFILE=~/.history
export ENVDIR=~/Git/ENV
export ENVFILES=$ENVDIR/envfiles

[[ -f ~/.normal ]] && export NORMAL=1
[[ -f ~/.keeppath ]] && export KEEPPATH=$PATH

. ~/.envpurge
. ~/.bloader $ENVFILES/_${USER^^}

# because LXDE has vte?
[[ $PROMPT_COMMAND =~ __vte ]] && PROMPT_COMMAND=${PROMPT_COMMAND#* } || :

prompt
