clear
[[ $SHLVL -eq 1 ]] || return 0
[[ -f $LA ]] && { ssh-agent -k; rm $LA $SA; }
[[ -f $SMAP ]] && rm $SMAP
printf "%s closing subshell @ %s\n\n" $(hostname):$LOGNAME "$(date)"
fortune=$(type -p fortune)
[[ $fortune ]] || return 0
read -t 5 -p 'fortune? '
[[ ${REPLY:-n} =~ ^[yY] ]] || exit 0
$fortune
printf "\n"
read -p 'pause...'
