[[ $- =~ i ]] || return 0

trap "date >> $HISTFILE; history -a" HUP INT QUIT KILL TERM

set -C -b -o vi
shopt -s extglob

# set some basic items

umask 0022
export HISTFILE=~/.history
export ENVDIR=~/Env
export ENVFILES=$ENVDIR/envfiles/LOADLIST
. $ENVDIR/envfiles/bashrcfuncs

envpurge
bloader

# because LXDE has vte?
[[ $PROMPT_COMMAND =~ __vte ]] && PROMPT_COMMAND= || :

prompt
