#-*-sh-*-
clear
[[ $SHLVL -eq 1 ]] || return 0
[[ -z $SSH_CLIENT ]] || return 0
[[ $SSH_AGENT_PID ]] && ssh-agent -k
rm $AGENTFILE ~/.agentfile
printf "%s closing subshell @ %s\n\n" $(hostname):$LOGNAME "$(date)"
fortune=$(type -p fortune)
[[ $fortune ]] || return 0
read -t 5 -p 'fortune? '
[[ ${REPLY:-n} =~ ^[yY] ]] || exit 0
$fortune
printf "\n"
read -p 'pause...'
