
# first we need to clear up the crap from the system
. ~/.envpurge

# set some basic items
export TZ=America/New_York
umask 0022

export PRINTER=local #this is a printer class
shopt -s extglob

PS1='\h:\w \u\$ '

export CDPATH=".:..:../..:~"
cd ~
. ~/.bashrc
