
# vim: ai si sw=4 sts=4 et ft=sh

# first we need to clear up the crap from the system

complete -r
unalias -a
unset -f $(compgen -A function)
unset ${!LC_*}

export PATH=/usr/bin:/usr/bin/core_perl
export MANPATH=/usr/share/man
export TZ=America/New_York
LANG=en_US.UTF-8
umask 0022

shopt -s extglob

PS1='\h:\w \u\$ '

export CDPATH=".:..:../..:~"

[[ $(compgen -e | grep -c SSH) -gt 0 ]] || eval "$(ssh-agent)"

export TERM=xterm-256color
tset

. ~/.bashrc
