

clear
[[ ! -L $SMAP ]] || rm $SMAP
[[ $SHLVL -eq 1 ]] || return 0
[[ -L $LA ]] || { ssh-agent -k; rm $LA; }
printf "%s closing subshell @ %s\n\n" $(hostname):$LOGNAME "$(date)"
read -t 5 -p 'fortune? '
[[ ${REPLY:-n} =~ ^[yY] ]] || exit 0
FORTUNE=/usr/games/fortune
[[ -x $FORTUNE ]] || FORTUNE=/usr/bin/fortune
$FORTUNE
printf "\n"
read -p 'pause...'
