clear
FORTUNE=/usr/games/fortune
[[ -x $FORTUNE ]] || FORTUNE=/usr/bin/fortune
$FORTUNE
printf "\n"
sleep 5
(( $SHLVL - 1 )) && return 0
[[ -n "$SSH_AGENT_PID" ]] && ssh-agent -k
printf "%s closed subshell @ %s\n\n" $(hostname):$LOGNAME "$(date)"
