

clear
[[ $SHLVL -eq 1 ]] || return 0
[[ -v SSH_AGENT_PID ]] && ssh-agent -k
[[ -s ~/.ssh/loadagent-${HOSTNAME} ]] && rm ~/.ssh/loadagent-${HOSTNAME}
printf "%s closing subshell @ %s\n\n" $(hostname):$LOGNAME "$(date)"
read -t 5 -p 'fortune? '
[[ ${REPLY:-n} =~ ^[yY] ]] || exit 0
FORTUNE=/usr/games/fortune
[[ -x $FORTUNE ]] || FORTUNE=/usr/bin/fortune
$FORTUNE
printf "\n"
read -p 'pause...'
