
#clear
[[ $SHLVL -eq 1 ]] || exit 0
[[ -z $SSH_CLIENT ]] || exit 0
#[[ $SSH_AGENT_PID ]] && ssh-agent -k
#[[ -e $AGENTFILE ]] || rm ~/.agentfile
printf "%s closing subshell @ %s\n\n" $(hostname):$LOGNAME "$(date)"
read -p 'pause'
fortune=$(type -p fortune)
[[ -n $fortune ]] && $fortune || exit 0
printf "\n"
read -p 'pause...'
