
[[ -L ~/Env/testing ]] && read -e -i yes -p 'found testing branch. use? ' -t 3 opt
[[ ${opt:-no} =~ ^[yY] ]] && ENVTAG=testing || ENVTAG=current
declare -rx ENVTAG
run=~/Env/$ENVTAG/main/bash_profile
[[ -s $run ]] && . $run
