
if [[ -L ~/Env/testing ]]; then
    declare -rx ENVTAG=testing
else
    declare -rx ENVTAG=current
fi
ln -s -f ~/Env/$ENVTAG/dotfiles/tmux.conf ~/.tmux.conf
ln -s -f ~/Env/$ENVTAG/syncdirs/vim ~/.vim
. ~/Env/$ENVTAG/dotfiles/bashrc
