: source $VIMDIR/exrc

:colorscheme darkblue
:hi MatchParen cterm=none ctermbg=none ctermfg=none
:hi StatusLine ctermbg=black
:set statusline=%f\ %m%=%l\ %c,%V\ %p%%
:set laststatus=2
:set t_Co=256
:syntax on
:set nohls
":colorscheme darkblue
:set formatoptions=2coqr
:set comments=s1:/*,mb:*,xe:*/,://,n:#,:%,:XCOMM,n:>,fb:-
:set smarttab
:set shiftround
:set tildeop
:set modelines=5
:set nowrap
:set ruler
:filetype plugin indent on
:set iskeyword+=:
" this turns off the matchparen annoyance
:let g:loaded_matchparen=1
":let g:is_bash=1 "should not be needed with filetype plugin 

":source $VIM/vim-cursor

":source $VIM/vim-tmux

"put all swap files together in one place
if isdirectory($VIMHOME . '.swaps') == 0
    :silent !mkdir -p $VIMHOME/.swaps >/dev/null 2>&1
endif
set dir=$VIMHOME/.swaps//

"put all backup files together in one place
if isdirectory($VIMHOME . '.backups') == 0
    :silent !mkdir -p $VIMHOME/.backups >/dev/null 2>&1
endif
set backupdir=$VIMHOME/.backups//
set backup

"put all undo files together in one place
if isdirectory($VIMHOME . '.undos') == 0
    :silent !mkdir -p $VIMHOME/.undos >/dev/null 2>&1
endif
set undodir=$VIMHOME/.undos//
set undofile

" yes, folding is good
"set foldcolumn=4
"set foldmethod=marker
"set foldmarker=AzA,ZaZ

"abbreviations and mappings
:source $VIMDIR/vimrc-abbr
:source $VIMDIR/vimrc-maps
