: source $ViM/exrc

:set t_Co=256
:syntax on
:set nohls
:colorscheme darkblue
:set formatoptions=2coqr
:set comments=s1:/*,mb:*,xe:*/,://,n:#,:%,:XCOMM,n:>,fb:-
:set smarttab
:set shiftround
:set tildeop
:set modelines=5
:set nowrap
:set ruler
:filetype plugin indent on
:set iskeyword+=:
:hi MatchParen cterm=none ctermbg=none ctermfg=none
" this turns off the matchparen annoyance
:let g:loaded_matchparen=1
":let g:is_bash=1 "should not be needed with filetype plugin 

":source $ViM/vim-cursor

":source $ViM/vim-tmux

"put all swap files together in one place
if isdirectory($ViM . 'swaps') == 0
    :silent !mkdir -p $ViM/swaps >/dev/null 2>&1
endif
set dir=$ViM/swaps//

"put all backup files together in one place
if isdirectory($ViM . 'backups') == 0
    :silent !mkdir -p $ViM/backups >/dev/null 2>&1
endif
set backupdir=$ViM/backups//
set backup

"put all backup files together in one place
if isdirectory($ViM . 'undos') == 0
    :silent !mkdir -p $ViM/undos >/dev/null 2>&1
endif
set undodir=$ViM/undos//
set undofile

" yes, folding is good
set foldcolumn=4
set foldmethod=marker
set foldmarker=AzA,ZaZ

"abbreviations
:source $ViM/vimrc-abbr
:source $ViM/vimrc-maps
